FROM node:alpine
WORKDIR /blog
RUN apk add nginx&& mkdir /var/run/nginx &&\
    sed -i 's/return 404/root \/blog\/public/g' \/etc/nginx/conf.d/default.conf  &&\
    npm install hexo -g
COPY docker-entry.sh /docker-entry.sh
EXPOSE 80
CMD ["/docker-entry.sh"]